export const reimTypes = {
  ADD_REIM: "ADD_REIM", // TO LIST
  EST_REIM_ITEMS: "EST_REIM_ITEMS",
  GET_SINGLE_REIM: "GET_SINGLE_REIM",
  SUBMIT_REIM: "SUBMIT_REIM", // TO DATABASE
  UPDATE_AMOUNT: "UPDATE_AMOUNT",
  UPDATE_APPROVER: "UPDATE_APPROVER",
  UPDATE_DESC: "UPDATE_DESC",
  UPDATE_REIM: "UPDATE_REIM",
  UPDATE_REIM_USERNAME: "UPDATE_REIM_USERNAME",
  UPDATE_STATUS: "UPDATE_STATUS",
  UPDATE_SUBMIT_TIME: "UPDATE_SUBMIT_TIME",
  UPDATE_TIME: "UPDATE_TIME",
  UPDATE_TITLE: "UPDATE_TITLE",
  UPDATE_TYPE: "UPDATE_TYPE"
};
