export const userTypes = {
  ADD_USER: 'ADD_USER',
  CHANGE_ERR: 'CHANGE_ERR',
  FIND_USER: 'FIND_USER', 
  LOG_OUT: 'LOG_OUT',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_FNAME: 'UPDATE_FNAME',
  UPDATE_LNAME: 'UPDATE_LNAME',
  UPDATE_PASS: 'UPDATE_PASS',
  UPDATE_ROLE: 'UPDATE_ROLE', 
  UPDATE_USERINFO: 'UPDATE_USERINFO',
  UPDATE_USERNAME: 'UPDATE_USERNAME',
}